#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "prance",
#   "pyyaml",
#   "ruamel.yaml",
# ]
# ///
"""Build `entity_to_table_mapping.yml` from DBML / SQL DDL schema files.

Identity mapping only: every `<table_name>` maps to itself. See SKILL.md.

Reuses `aibdd-core` spec_parsers (`dispatch_spec_parser`) so DBML / MySQL /
PostgreSQL / MSSQL parsing logic stays in one place.

Usage:
    python3 build_mapping.py <DATA_DIR>
    DATA_DIR=specs/shared python3 build_mapping.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

_THIS_FILE = Path(__file__).resolve()
# parents[0]=scripts, [1]=aibdd-table-to-entity, [2]=skills root
_AIBDD_CORE_LIB = (
    _THIS_FILE.parents[2] / "aibdd-core" / "scripts" / "lib"
)
if str(_AIBDD_CORE_LIB) not in sys.path:
    sys.path.insert(0, str(_AIBDD_CORE_LIB))

from shared.spec_parsers.dispatcher import dispatch_spec_parser  # noqa: E402
from shared.spec_parts import PartKind  # noqa: E402

SCHEMA_SUFFIXES = (".dbml", ".mysql.sql", ".pg.sql", ".mssql.sql")


def _scan_schema_files(data_dir: Path) -> list[Path]:
    files: list[Path] = []
    for path in data_dir.rglob("*"):
        if not path.is_file():
            continue
        name = path.name.lower()
        if any(name.endswith(suffix) for suffix in SCHEMA_SUFFIXES):
            files.append(path)
    return sorted(files)


def _extract_tables(path: Path) -> list[str]:
    parser = dispatch_spec_parser(path)
    return [
        part.table_name
        for part in parser.parse(path)
        if part.kind == PartKind.table
    ]


def _format_yaml(table_names: list[str]) -> str:
    header = "# DO NOT EDIT — generated by aibdd-table-to-entity\n"
    if not table_names:
        return header + "entity_to_table_mapping: []\n"
    lines = ["entity_to_table_mapping:"]
    lines.extend(f"  - {name}: {name}" for name in table_names)
    return header + "\n".join(lines) + "\n"


def build_mapping(data_dir: Path) -> int:
    if not data_dir.is_dir():
        sys.stderr.write(
            f"DATA_DIR not found: {data_dir} — run /aibdd-kickoff to create it\n"
        )
        return 2

    schema_files = _scan_schema_files(data_dir)
    table_origin: dict[str, Path] = {}
    table_order: list[str] = []
    dbml_count = 0
    ddl_count = 0

    for schema_file in schema_files:
        if schema_file.name.lower().endswith(".dbml"):
            dbml_count += 1
        else:
            ddl_count += 1
        for table_name in _extract_tables(schema_file):
            if table_name in table_origin:
                sys.stderr.write(
                    f"duplicate table {table_name!r}: "
                    f"{table_origin[table_name]} and {schema_file}\n"
                )
                return 3
            table_origin[table_name] = schema_file
            table_order.append(table_name)

    output_path = data_dir / "entity_to_table_mapping.yml"
    new_content = _format_yaml(table_order)

    if output_path.is_file() and output_path.read_bytes() == new_content.encode():
        action = "unchanged"
    else:
        output_path.write_text(new_content)
        action = "wrote"

    print(
        f"scanned {len(schema_files)} schema file(s) "
        f"(DBML={dbml_count}, DDL={ddl_count}); "
        f"{len(table_order)} table(s) extracted"
    )
    print(f"{action}: {output_path.resolve()} ({len(table_order)} entries)")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) >= 2:
        data_dir = Path(argv[1])
    elif "DATA_DIR" in os.environ:
        data_dir = Path(os.environ["DATA_DIR"])
    else:
        sys.stderr.write("usage: build_mapping.py <DATA_DIR>  (or set DATA_DIR env)\n")
        return 1
    return build_mapping(data_dir)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
