Feature: build entity_to_table_mapping.yml from DBML

  Rule: DBML 的 Table 以 table name 作為 Entity mapping
    Example: single DBML file with two tables
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        Table orders {
          id int [pk]
        }
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - users: users
          - orders: orders
        """

  Rule: DBML 跨檔重複 table 應被拒絕
    Example: same table name in two DBML files
      Given a temporary data directory
      And a schema file "a.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      And a schema file "b.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 3
      And CLI stderr should contain "duplicate table 'users'"

  Rule: DBML 相同內容第二次執行印 unchanged 不重寫檔案
    Example: running twice with unchanged DBML schema
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table users {
          id int [pk]
        }
        """
      When build_mapping CLI is run against the data directory
      And build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And CLI stdout should contain "unchanged"

  Rule: DATA_DIR 可由環境變數提供給 DBML mapping
    Example: DATA_DIR env var set, no CLI argument
      Given a temporary data directory
      And a schema file "schema.dbml" with content:
        """
        Table products {
          id int [pk]
        }
        """
      When build_mapping CLI is run with DATA_DIR env var pointing to the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - products: products
        """

  Rule: 含 0 個 table 的合法 DBML 檔不報錯
    Example: DBML file with no table definitions
      Given a temporary data directory
      And a schema file "empty.dbml" with content:
        """
        // no tables here
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping: []
        """
