Feature: build entity_to_table_mapping.yml from MS SQL DDL

  Rule: MS SQL DDL 的 CREATE TABLE 以 table name 作為 Entity mapping
    Example: .mssql.sql file with bracket-quoted owner prefix and IDENTITY
      Given a temporary data directory
      And a schema file "schema.mssql.sql" with content:
        """
        CREATE TABLE [dbo].[customers] (
          [id] INT IDENTITY(1,1) NOT NULL,
          [name] NVARCHAR(100) NOT NULL,
          CONSTRAINT [PK_customers] PRIMARY KEY ([id])
        );
        CREATE TABLE [dbo].[invoices] (
          [id] INT IDENTITY(1,1) NOT NULL,
          [customer_id] INT NOT NULL,
          CONSTRAINT [PK_invoices] PRIMARY KEY ([id])
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping:
          - customers: customers
          - invoices: invoices
        """

  Rule: MS SQL DDL 跨檔重複 table 應被拒絕
    Example: same table name in two MS SQL DDL files
      Given a temporary data directory
      And a schema file "a.mssql.sql" with content:
        """
        CREATE TABLE [dbo].[customers] (
          [id] INT IDENTITY(1,1) NOT NULL,
          CONSTRAINT [PK_customers] PRIMARY KEY ([id])
        );
        """
      And a schema file "b.mssql.sql" with content:
        """
        CREATE TABLE [dbo].[customers] (
          [id] INT IDENTITY(1,1) NOT NULL,
          CONSTRAINT [PK_customers] PRIMARY KEY ([id])
        );
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 3
      And CLI stderr should contain "duplicate table 'customers'"

  Rule: 含 0 個 table 的合法 MS SQL DDL 檔不報錯
    Example: MS SQL DDL file with no table definitions
      Given a temporary data directory
      And a schema file "empty.mssql.sql" with content:
        """
        -- no tables here
        """
      When build_mapping CLI is run against the data directory
      Then CLI exit code is 0
      And the generated mapping should equal:
        """
        # DO NOT EDIT — generated by aibdd-table-to-entity
        entity_to_table_mapping: []
        """
